#! /bin/csh -f

#------------------------------------------------------------------
# Copy file from CCSM inputdata directory
# Searches locally, on mass store, and on other machines
# "Usage: ccsm_getinput [dir/]file [dir/][file]"
#------------------------------------------------------------------

# return gracefully in all cases, ccsm4 doesn't 
# support prestaging at this point.  this exit should
# be removed and the logic below "adjusted" for ccsm4
# to support prestaging in the future.
echo "WARNING: ccsm_getinput is OFF, no prestaging support in ccsm4 right now"
exit 0

